---
inherit_from: .rubocop_todo.yml

inherit_gem:
  voxpupuli-test: rubocop.yml

Lint/ConstantDefinitionInBlock:
  Enabled: false

RSpec/ExpectInHook:
  Enabled: false

RSpec/LeakyConstantDeclaration:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/StubbedMock:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false
