---
Gemfile:
  optional:
    ':test':
      - gem: 'rspec-its'
      - gem: 'retries'
spec/spec_helper.rb:
  spec_overrides: "require 'rspec/its'"
.github/workflows/ci.yml:
  pidfile_workaround: CentOS
.rubocop.yml:
  unmanaged: true
