#!/bin/bash
#
# Returns 0 if the given plugin is installed with the given version
#
# Takes 2 args: <plugin> <version>

name=$1
desired_ver=$2
plugin_dir="<%= scope.lookupvar('plugin_dir') %>"
manifest="${plugin_dir}/${name}/META-INF/MANIFEST.MF"

if [ -z $name ]; then
  echo 'Plugin name must be specified' 1>&2
  exit 1
fi

if [ -z $desired_ver ]; then
  desired_ver="0"
fi

# If no version specified (ie. version defaulted to 0), check if any version
# of the plugin is installed, and if it is, then exit 0
if [[ "$desired_ver" == "0" ]]; then
  test -f "${plugin_dir}/${name}.hpi" || test -f "${plugin_dir}/${name}.jpi"
  if [ $? -eq 0 ]; then
    echo "${name} plugin is installed"
    exit 0
  fi
fi

# Check the plugin manifest file for the installed version and compare that with
# the provided desired plugin version and exit with an appropriate code

if [ ! -f $manifest ]; then
  echo 'Unable to determine plugin version' 1>&2
  exit 1
fi

installed_ver=`cat $manifest | grep -e 'Plugin-Version:'`

echo $installed_ver | grep -e "\s${desired_ver}\s" >/dev/null
if [ $? -ne 0 ]; then
  echo "Installed: ${name} ${installed_ver}" 1>&2
  exit 1
fi

echo "${name} plugin ${desired_ver} is installed"
exit 0
